import { StyleSheet } from 'react-native';
import colors from '../../utils/colors';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
        paddingTop: 40,
    },
    notClickableButtonWrapper: {
        backgroundColor: colors.thunderRed,
        borderWidth: 1,
        borderColor: colors.thunderRed,
        height: 40,
        borderRadius: 5,
        marginVertical: 20,
        marginHorizontal: 5,
        alignItems: 'center',
        justifyContent: 'center',
        opacity: .6,
    },
    buttonWrapper: {
        backgroundColor: colors.thunderRed,
        borderWidth: 1,
        borderColor: colors.thunderRed,
        height: 40,
        borderRadius: 5,
        marginVertical: 20,
        marginHorizontal: 5,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonText: {
        textAlign: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    bottomBar: {
        flex: 1,
        backgroundColor: colors.bottomNav,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 10,
        height: 49,
        position: 'absolute',
        bottom: 0,
        right: 0,
        left: 0,
    },
    backButtonWrapper: {
        backgroundColor: colors.gray[4],
        borderWidth: 1,
        borderColor: colors.gray[4],
        height: 35,
        borderRadius: 5,
        marginHorizontal: 5,
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1,
    },
    backButtonWrapperText: {
        marginLeft: 4,
        fontSize: 18,
        color: colors.white,
        fontWeight: 'bold',
    }
})
