import { StyleSheet } from 'react-native';
import colors from '../../utils/colors';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.bottomNav,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        height: 49,
        position: 'absolute',
        bottom: 0,
        right: 0,
        left: 0,
    },
    startOverButton: {
        backgroundColor: colors.green,
        borderColor: colors.green,
        borderWidth: 1,
        borderRadius: 64,
        height: 30,
        width: 120,
        alignItems: 'center',
        justifyContent: 'center',
    },
    startOverText: {
        color: colors.white,
        fontWeight: 'bold',
        fontSize: 18,
    },
    deleteButton: {
        backgroundColor: colors.bottomNav,
        borderColor: colors.bottomNav,
        borderWidth: 10,
        borderRadius: 64,
        height: 30,
        width: 120,
        alignItems: 'center',
        justifyContent: 'center',
    },
    deleteButtonNotClickable: {
        backgroundColor: colors.bottomNav,
        borderColor: colors.bottomNav,
        borderWidth: 10,
        borderRadius: 64,
        height: 30,
        width: 120,
        alignItems: 'center',
        justifyContent: 'center',
        opacity: .4,
    },
    deleteButtonTextWrapper: {
        flexDirection: 'row',
    },
    deleteButtonText: {
        color: colors.thunderRed,
        fontWeight: 'bold',
        fontSize: 18,
    },
    halfCircle: {
        backgroundColor: colors.bottomNav,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 40,
        width: 80,
        borderBottomLeftRadius:34,
        borderBottomRightRadius:34,
    },
    halfCircleText: {
        color: colors.bottomNavText,
        fontWeight: 'bold',
        margin: 2,
        fontSize: 16,
    },
    icon: {
        marginLeft: 6,
    },
})
